### ISSUE TITLE
Plugin installed but no lightbox opens for images?

### ISSUE THREAD

**Issue by pwFoo** [june07/nodebb-plugin-lightgallery#1]
Hi @june07 , 
I installed and activated the plugin, but images still open in a new tab instead of lightbox / lightgallery?

**Comment by june07** [comment]
Did you try rebuild and restart?

**Comment by pwFoo** [comment]
Hi, more than once... Also disabled, activated and rebuild again. 
But rebuild and restart one more time... now it's working. 

Strange... but works now...
