### ISSUE TITLE
lightgallery plugin does not work consistently in NodeBB v3.1.3

### ISSUE THREAD

**Issue by val-kulkov** [june07/nodebb-plugin-lightgallery#12]
Running Google Chrome Version 113.0.5672.92 (Official Build) (64-bit) on the client, NodeBB v3.1.3 and Nginx 1.22.1 on the server; invoking "empty cache and hard reload" in Chrome to make sure that the page in question is loaded anew.

What happens: when clicking on an image, the browser loads the image itself located at /assets/uploads/files/<filename>.jpg and the lightgallery plugin is not called. The console shows "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enableQuickReply')" but this error does not seem to be specific to the lightgallery plugin as it appears on all pages in NodeBB v3.1.3.

Reloading the page with images seems to resolve the problem: after a page reload, the lightgallery plugin starts working normally, only producing a 404 not found error for /plugins/nodebb-plugin-lightgallery/images/loading.gif.

However, if I go back to the forum categories and then select the page with images, the problem re-appears. Clicking on an image brings up the image file and the lightgallery plugin is not called.

**Comment by june07** [comment]
You're more than welcome to submit a PR and I'll work with you to get it merged.

**Comment by june07** [comment]
Just to give a bit more info on this... when installing from source in an attempt to verify your issue and fix, I get tons of dependency errors including one about phantomjs not being present which was needed by lightgallery 1.0. The best course of action for this project would likely be to simply upgrade the lightgallery dependency to 2.0.

I don't have a lot of time to work on this project anymore so I'm sorry I can't help you more.

**Comment by val-kulkov** [comment]
Thanks for the tip, @june07 . It has been years since I did some work with NodeJS, so I am going to have to refresh my memory and possibly re-learn NodeJS before I can attempt to do something with this issue. Not sure I can do it in the near future.
