### ISSUE TITLE
Links opening in gallery

### ISSUE THREAD

**Issue by chocolate012** [june07/nodebb-plugin-lightgallery#3]
When the lightgallery Plugin is installed if there is a link in the post after there is an image the link will not open but instead the gallery will open
see for example https://shutfim.com/topic/234/microsoft-power-toys/11

**Comment by june07** [comment]
Would help to be able to get the pictures to render, however you must  be registered for that site.  Unfortunately, I don't know the answer to the Hebrew registration question.  I'd be happy to look more into this if you can provide an account on the board.

**Comment by chocolate012** [comment]
613
Thanks

**Comment by june07** [comment]
I will need to push this to the weekend but I'll definitely try to update by then.

**Comment by june07** [comment]
Please give the most recent version (1.0.13) a go and let me know if that fixes your issue...

**Comment by chocolate012** [comment]
Yes
Thanks

**Comment by chocolate012** [comment]
The issue still persists on Mobile

**Comment by june07** [comment]
Funny, works fine for me on mobile.

**Comment by chocolate012** [comment]
Try the link in this post https://shutfim.com/post/1005


--

**Comment by june07** [comment]
I did and they go to GitHub.

**Comment by chocolate012** [comment]
[Video_2020-05-25_184201.zip](https://github.com/june07/nodebb-plugin-lightgallery/files/4677950/Video_2020-05-25_184201.zip)

**Comment by june07** [comment]
Watched.  Still, it's working fine for me both on an actual mobile device and in the emulated browser environment.  Maybe you should try "Empty Cache and Hard Reload" and/or trying on a different mobile device...

**Comment by june07** [comment]
Just checking in on this...

**Comment by chocolate012** [comment]
All sorted, Thanks
